let biodata = "Welcome my biodata"
document.getElementById("biodata").innerHTML = biodata;
let nama = "RADI MAULANA TSAQIF"
document.getElementById("nama").innerHTML = nama;
let kelas = "XI PPLG 1"
document.getElementById("kelas").innerHTML = kelas;
let noHP = "083844108250"
document.getElementById("noHP").innerHTML = noHP;
let Alamat = "KAMPUNG DALEUM"
document.getElementById("Alamat").innerHTML = Alamat;
let ttl = "TASIKMALAYA, 05 JANUARI 2007"
document.getElementById("ttl").innerHTML = ttl;